name: automl_vision
channels:
- anaconda
- conda-forge
- pytorch
dependencies:
- python=3.7
- numpy==1.18.5
- pandas==0.25.1
- pytorch==1.7.1
- torchvision==0.8.2
- pytest
- pip:
  - azureml-core==1.25.0
  - azureml-dataset-runtime==1.25.0
  - azureml-contrib-dataset==1.25.0
  - azureml-telemetry==1.25.0
  - azureml-automl-core==1.25.0
  - azureml-automl-runtime==1.25.0.post1
  - azureml-train-automl-client==1.25.0
  - azureml-defaults==1.25.0
  - azureml-interpret==1.25.0
  - azureml-train-automl-runtime==1.25.0
  - azureml-train-automl==1.25.0
  - azureml-contrib-automl-dnn-vision==1.25.0
  - azureml-designer-core==0.0.59