name: automl
channels:
- anaconda
- conda-forge
- pytorch
dependencies:
- python=3.6.2
- pytorch==1.7.1
- torchvision==0.8.2
- numpy>=1.16.0,<1.19.0
- pandas==0.25.1
- scikit-learn==0.22.1
- py-xgboost<=0.90
- fbprophet==0.5
- holidays==0.9.11
- psutil>=5.2.2,<6.0.0
- pytest
- pip:
  - azureml-core==1.25.0
  - azureml-defaults==1.25.0
  - azureml-dataset-runtime==1.25.0
  - azureml-contrib-dataset==1.25.0
  - azureml-telemetry==1.25.0
  - azureml-automl-core==1.25.0
  - azureml-automl-runtime==1.25.0.post1
  - azureml-train-automl==1.25.0
  - azureml-train-automl-runtime==1.25.0
  - azureml-train-automl-client==1.25.0
  - azureml-contrib-automl-dnn-vision==1.25.0
  - azureml-interpret==1.25.0
  - azureml-designer-core==0.0.59
  - xgboost==1.1.1
